# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 15:28
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('winner', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('wins', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_number', models.IntegerField(default=0)),
                ('number_of_teams', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_per_day', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('number_of_team', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
                ('number_of_pool', models.IntegerField(default=1)),
                ('type', models.IntegerField()),
                ('available_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserWrapper'),
        ),
        migrations.AddField(
            model_name='pool',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tournament'),
        ),
        migrations.AddField(
            model_name='point',
            name='pool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Pool'),
        ),
        migrations.AddField(
            model_name='match',
            name='pool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Pool'),
        ),
    ]
