# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 19:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('matches_per_day', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('number_of_team', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
                ('number_of_pool', models.IntegerField(default=1)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('winner', models.CharField(default=b'0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('wins', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_number', models.IntegerField(default=0)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.LoginCredential')),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='pool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Pool'),
        ),
        migrations.AddField(
            model_name='match',
            name='pool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Pool'),
        ),
    ]
