# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='number_of_teams',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
