# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_players', models.PositiveIntegerField()),
                ('sport', models.CharField(max_length=50)),
            ],
        ),
    ]
