# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserWrapper'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tournament'),
        ),
    ]
