# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sportspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
