# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170603_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginCredentials',
            new_name='LoginCredential',
        ),
    ]
