# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170819_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.BigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='login',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.UserWrapper'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Tournament'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Team'),
        ),
    ]
