# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170819_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='login',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.UserWrapper'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Tournament'),
        ),
    ]
