# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170704_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=200)),
                ('user_wrapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserWrapper')),
            ],
        ),
    ]
