# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_googleuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.UserWrapper')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Tournament')),
            ],
        ),
    ]
