# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170603_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
