# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0003_delete_sportsspecification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_players', models.PositiveIntegerField()),
                ('sport', models.CharField(max_length=50)),
            ],
        ),
    ]
