# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170603_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincredential',
            name='matches_per_day',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logincredential',
            name='number_of_team',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='user_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
