# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_categories_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
