# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 09:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170603_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincredential',
            name='matches_per_day',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='number_of_team',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
